# Generated by Django 5.0 on 2024-02-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
